// config.js
// Central API endpoints, shared state, and Washington city search data.

const SHELTER_SEARCH_RADIUS_MILES = 90;
const INCIDENT_RESOURCE_RADIUS_MILES = 85;
const CITY_FIRE_RADIUS_MILES = 90;
const WA_ENVELOPE = '-124.95,45.45,-116.85,49.05';
const SIMULATION_FIRE_DATE = '2024-07-04';
const SIMULATION_FIRE_DATE_LABEL = 'July 4, 2024';
const DNR_FIRE_STATS_2024_URL = 'https://gis.dnr.wa.gov/site3/rest/services/Public_Wildfire/WADNR_PUBLIC_WD_WildFire_Data/MapServer/2/query';
const FIRE_PERIMETER_2024_URL = 'https://services1.arcgis.com/CD5mKowwN6nIaqd8/arcgis/rest/services/project_landscape_planning_tool_fire_perimeter_history/FeatureServer/0/query';

let allShelters = [];
let allFires = [];
let shelterMarkers = [];
let fireMarkers = [];
let searchQuery = '';
let selectedCity = null;
let selectedCityMarker = null;
let selectedFire = null;

const WASHINGTON_CITIES = [
  { name: 'Aberdeen', region: 'Grays Harbor County', lat: 46.9754, lon: -123.8157 },
  { name: 'Anacortes', region: 'Skagit County', lat: 48.5126, lon: -122.6127 },
  { name: 'Arlington', region: 'Snohomish County', lat: 48.1987, lon: -122.1251 },
  { name: 'Auburn', region: 'King County', lat: 47.3073, lon: -122.2285 },
  { name: 'Bellingham', region: 'Whatcom County', lat: 48.7519, lon: -122.4787 },
  { name: 'Bellevue', region: 'King County', lat: 47.6101, lon: -122.2015 },
  { name: 'Bothell', region: 'King/Snohomish County', lat: 47.7623, lon: -122.2054 },
  { name: 'Bremerton', region: 'Kitsap County', lat: 47.5673, lon: -122.6326 },
  { name: 'Bickleton', region: 'Klickitat County', lat: 46.0096, lon: -120.3062 },
  { name: 'Cashmere', region: 'Chelan County', lat: 47.5223, lon: -120.4698 },
  { name: 'Centralia', region: 'Lewis County', lat: 46.7162, lon: -122.9543 },
  { name: 'Chelan', region: 'Chelan County', lat: 47.8408, lon: -120.0168 },
  { name: 'Cheney', region: 'Spokane County', lat: 47.4874, lon: -117.5758 },
  { name: 'Cle Elum', region: 'Kittitas County', lat: 47.1954, lon: -120.9392 },
  { name: 'Colville', region: 'Stevens County', lat: 48.5466, lon: -117.9043 },
  { name: 'Connell', region: 'Franklin County', lat: 46.6635, lon: -118.8611 },
  { name: 'Coulee Dam', region: 'Okanogan County', lat: 47.9654, lon: -118.9764 },
  { name: 'Darrington', region: 'Snohomish County', lat: 48.2554, lon: -121.6015 },
  { name: 'Eatonville', region: 'Pierce County', lat: 46.8673, lon: -122.2660 },
  { name: 'Ellensburg', region: 'Kittitas County', lat: 46.9965, lon: -120.5478 },
  { name: 'Enumclaw', region: 'King County', lat: 47.2043, lon: -121.9915 },
  { name: 'Ephrata', region: 'Grant County', lat: 47.3176, lon: -119.5537 },
  { name: 'Everett', region: 'Snohomish County', lat: 47.9789, lon: -122.2021 },
  { name: 'Federal Way', region: 'King County', lat: 47.3223, lon: -122.3126 },
  { name: 'Forks', region: 'Clallam County', lat: 47.9504, lon: -124.3855 },
  { name: 'Goldendale', region: 'Klickitat County', lat: 45.8207, lon: -120.8217 },
  { name: 'Grand Coulee', region: 'Grant County', lat: 47.9390, lon: -119.0033 },
  { name: 'Harrah', region: 'Yakima County', lat: 46.4043, lon: -120.5420 },
  { name: 'Hoquiam', region: 'Grays Harbor County', lat: 46.9809, lon: -123.8893 },
  { name: 'Issaquah', region: 'King County', lat: 47.5301, lon: -122.0326 },
  { name: 'Kelso', region: 'Cowlitz County', lat: 46.1468, lon: -122.9084 },
  { name: 'Keller', region: 'Ferry County', lat: 48.0832, lon: -118.7120 },
  { name: 'Kennewick', region: 'Benton County', lat: 46.2087, lon: -119.1190 },
  { name: 'Kent', region: 'King County', lat: 47.3809, lon: -122.2348 },
  { name: 'Kettle Falls', region: 'Stevens County', lat: 48.6107, lon: -118.0558 },
  { name: 'Leavenworth', region: 'Chelan County', lat: 47.5962, lon: -120.6615 },
  { name: 'Longview', region: 'Cowlitz County', lat: 46.1382, lon: -122.9382 },
  { name: 'Moses Lake', region: 'Grant County', lat: 47.1301, lon: -119.2781 },
  { name: 'Mount Vernon', region: 'Skagit County', lat: 48.4212, lon: -122.3340 },
  { name: 'Naches', region: 'Yakima County', lat: 46.7307, lon: -120.6995 },
  { name: 'Newport', region: 'Pend Oreille County', lat: 48.1796, lon: -117.0433 },
  { name: 'North Bend', region: 'King County', lat: 47.4957, lon: -121.7868 },
  { name: 'Oak Harbor', region: 'Island County', lat: 48.2932, lon: -122.6432 },
  { name: 'Ocean Shores', region: 'Grays Harbor County', lat: 46.9737, lon: -124.1563 },
  { name: 'Okanogan', region: 'Okanogan County', lat: 48.3610, lon: -119.5834 },
  { name: 'Olympia', region: 'Thurston County', lat: 47.0379, lon: -122.9007 },
  { name: 'Omak', region: 'Okanogan County', lat: 48.4107, lon: -119.5276 },
  { name: 'Pasco', region: 'Franklin County', lat: 46.2396, lon: -119.1006 },
  { name: 'Patterson', region: 'Benton County', lat: 45.9365, lon: -119.6110 },
  { name: 'Pateros', region: 'Okanogan County', lat: 48.0521, lon: -119.9034 },
  { name: 'Port Angeles', region: 'Clallam County', lat: 48.1181, lon: -123.4307 },
  { name: 'Port Townsend', region: 'Jefferson County', lat: 48.1170, lon: -122.7604 },
  { name: 'Pullman', region: 'Whitman County', lat: 46.7313, lon: -117.1796 },
  { name: 'Quincy', region: 'Grant County', lat: 47.2343, lon: -119.8526 },
  { name: 'Raymond', region: 'Pacific County', lat: 46.6865, lon: -123.7329 },
  { name: 'Renton', region: 'King County', lat: 47.4829, lon: -122.2171 },
  { name: 'Republic', region: 'Ferry County', lat: 48.6482, lon: -118.7378 },
  { name: 'Richland', region: 'Benton County', lat: 46.2804, lon: -119.2752 },
  { name: 'Ritzville', region: 'Adams County', lat: 47.1274, lon: -118.3797 },
  { name: 'Seattle', region: 'King County', lat: 47.6062, lon: -122.3321 },
  { name: 'Sedro-Woolley', region: 'Skagit County', lat: 48.5039, lon: -122.2361 },
  { name: 'Shelton', region: 'Mason County', lat: 47.2151, lon: -123.1007 },
  { name: 'Snoqualmie', region: 'King County', lat: 47.5287, lon: -121.8254 },
  { name: 'Spokane', region: 'Spokane County', lat: 47.6588, lon: -117.4260 },
  { name: 'Stehekin', region: 'Chelan County', lat: 48.3090, lon: -120.6565 },
  { name: 'Stevenson', region: 'Skamania County', lat: 45.6957, lon: -121.8845 },
  { name: 'Tacoma', region: 'Pierce County', lat: 47.2529, lon: -122.4443 },
  { name: 'Tonasket', region: 'Okanogan County', lat: 48.7052, lon: -119.4398 },
  { name: 'Toppenish', region: 'Yakima County', lat: 46.3774, lon: -120.3087 },
  { name: 'Twisp', region: 'Okanogan County', lat: 48.3635, lon: -120.1217 },
  { name: 'Vancouver', region: 'Clark County', lat: 45.6387, lon: -122.6615 },
  { name: 'Walla Walla', region: 'Walla Walla County', lat: 46.0646, lon: -118.3430 },
  { name: 'Wenatchee', region: 'Chelan County', lat: 47.4235, lon: -120.3103 },
  { name: 'White Salmon', region: 'Klickitat County', lat: 45.7276, lon: -121.4865 },
  { name: 'White Swan', region: 'Yakima County', lat: 46.3787, lon: -120.7329 },
  { name: 'Winthrop', region: 'Okanogan County', lat: 48.4779, lon: -120.1862 },
  { name: 'Yakima', region: 'Yakima County', lat: 46.6021, lon: -120.5059 },
  { name: 'Yelm', region: 'Thurston County', lat: 46.9420, lon: -122.6059 },
];

const HISTORICAL_2024_SHELTERS = [
  {
    name: 'Patterson Elementary School',
    fire: 'Big Horn Fire',
    type: 'Red Cross shelter',
    activeStart: '2024-07-25',
    activeEnd: '2024-07-27',
    opened: 'Opened July 2024 in Benton County for individuals and families displaced by the Big Horn Fire',
    address: '51409 Prior Ave, Patterson, WA 99345',
    city: 'Patterson',
    lat: 45.9365,
    lon: -119.6110,
    sourceName: 'InciWeb Big Horn Fire update',
    sourceUrl: 'https://inciweb.wildfire.gov/incident-publication/wases-big-horn-fire/big-horn-fire-pm-update-july-26-2024-07-27-2024',
  },
  {
    name: 'Chelan United Methodist Church',
    fire: 'Pioneer Fire',
    type: 'Red Cross shelter',
    activeStart: '2024-08-18',
    activeEnd: '2024-08-19',
    opened: 'Opened during 2024 Pioneer Fire evacuations; closure noted Aug. 19, 2024',
    address: '206 N Emerson St, Chelan, WA',
    city: 'Chelan',
    lat: 47.8408,
    lon: -120.0190,
    sourceName: 'InciWeb Pioneer Fire evacuation update',
    sourceUrl: 'https://inciweb.wildfire.gov/incident-publication/wases-pioneer/pioneer-fire-evacuation-level-updates-08-18-2024',
  },
  {
    name: 'Chelan Community Gym',
    fire: 'Pioneer Fire',
    type: 'Red Cross shelter',
    activeStart: '2024-07-28',
    activeEnd: '2024-08-09',
    opened: 'Established by the American Red Cross for Stehekin evacuees during Pioneer Fire Level 3 evacuation orders',
    address: '317 E Johnson Ave, Chelan, WA',
    city: 'Chelan',
    lat: 47.8404,
    lon: -120.0128,
    sourceName: 'Chelan County / Lake Chelan evacuation report',
    sourceUrl: 'https://lakechelannow.com/community-of-stehekin-under-level-evacuation/',
  },
  {
    name: 'Stehekin Ranch',
    fire: 'Pioneer Fire',
    type: 'evacuation refuge point',
    activeStart: '2024-07-28',
    activeEnd: '2024-07-28',
    opened: 'Listed as a local refuge point for people leaving Stehekin during Pioneer Fire Level 3 evacuation',
    address: 'Stehekin, WA',
    city: 'Stehekin',
    lat: 48.3467,
    lon: -120.7203,
    sourceName: 'KPQ Pioneer Fire evacuation report',
    sourceUrl: 'https://kpq.com/urgent-evacuation-alert-stehekin/',
  },
  {
    name: 'Stehekin State Airfield',
    fire: 'Pioneer Fire',
    type: 'evacuation refuge point',
    activeStart: '2024-07-28',
    activeEnd: '2024-07-28',
    opened: 'Listed as a local refuge point for people leaving Stehekin during Pioneer Fire Level 3 evacuation',
    address: 'Stehekin, WA',
    city: 'Stehekin',
    lat: 48.3460,
    lon: -120.7208,
    sourceName: 'KPQ Pioneer Fire evacuation report',
    sourceUrl: 'https://kpq.com/urgent-evacuation-alert-stehekin/',
  },
  {
    name: 'Buckner Orchard',
    fire: 'Pioneer Fire',
    type: 'evacuation refuge point',
    activeStart: '2024-07-28',
    activeEnd: '2024-07-28',
    opened: 'Listed as a local refuge point for people leaving Stehekin during Pioneer Fire Level 3 evacuation',
    address: 'Stehekin, WA',
    city: 'Stehekin',
    lat: 48.3248,
    lon: -120.6966,
    sourceName: 'KPQ Pioneer Fire evacuation report',
    sourceUrl: 'https://kpq.com/urgent-evacuation-alert-stehekin/',
  },
  {
    name: 'Stehekin Bakery',
    fire: 'Pioneer Fire',
    type: 'evacuation refuge point',
    activeStart: '2024-07-28',
    activeEnd: '2024-07-28',
    opened: 'Listed as a local refuge point for people leaving Stehekin during Pioneer Fire Level 3 evacuation',
    address: 'Stehekin, WA',
    city: 'Stehekin',
    lat: 48.3184,
    lon: -120.6865,
    sourceName: 'KPQ Pioneer Fire evacuation report',
    sourceUrl: 'https://kpq.com/urgent-evacuation-alert-stehekin/',
  },
  {
    name: 'Naches Valley High School',
    fire: 'Retreat Fire',
    type: 'Red Cross evacuation center',
    activeStart: '2024-07-26',
    activeEnd: '2024-07-27',
    opened: 'Opened July 2024 for Retreat Fire evacuees',
    address: '101 W 5th Ave, Naches, WA',
    city: 'Naches',
    lat: 46.7307,
    lon: -120.7048,
    sourceName: 'Northwest Public Broadcasting / local reports',
    sourceUrl: 'https://www.nwpb.org/nw-news/2024-07-26/intense-fire-week-forces-road-closures-and-evacuation-notices-in-wa',
  },
  {
    name: 'Harrah Elementary School',
    fire: 'Slide Ranch Fire',
    type: 'emergency shelter',
    activeStart: '2024-06-22',
    activeEnd: '2024-07-11',
    opened: 'Opened June 2024 for Slide Ranch Fire evacuees',
    address: '3851 Harrah Rd, Harrah, WA',
    city: 'Harrah',
    lat: 46.4054,
    lon: -120.5444,
    sourceName: 'KIT / Newstalk local report',
    sourceUrl: 'https://newstalkkit.com/fierce-slide-ranch-fire-forces-evacuations-destroys-homes/',
  },
  {
    name: 'White Swan Community Center',
    fire: 'Slide Ranch Fire',
    type: 'food and donation resource center',
    activeStart: '2024-06-22',
    activeEnd: '2024-07-03',
    opened: 'Opened June-July 2024 with food, clothing, cleaning supplies, meals, and donations for families who lost homes',
    address: 'White Swan, WA',
    city: 'White Swan',
    lat: 46.3787,
    lon: -120.7329,
    sourceName: 'NonStop Local / NBC Right Now',
    sourceUrl: 'https://www.nbcrightnow.com/news/white-swan-community-receives-overwhelming-support-donations-following-slide-ranch-fire/article_b8a71bee-3835-11ef-bd20-afcafee41056.html',
  },
  {
    name: 'Yakama Nation Boys and Girls Club',
    fire: 'Slide Ranch Fire',
    type: 'family support resource',
    activeStart: '2024-06-24',
    activeEnd: '2024-06-28',
    opened: 'Welcomed children of families affected by the Slide Ranch Fire from 8 a.m. to 5 p.m.',
    address: 'White Swan / Yakama Nation area, WA',
    city: 'White Swan',
    lat: 46.3787,
    lon: -120.7329,
    sourceName: 'NonStop Local / NBC Right Now',
    sourceUrl: 'https://www.nbcrightnow.com/news/slide-ranch-victims-move-forward-with-support-from-white-swan-community/article_f3f5574e-90ee-11ef-a931-b39427c75cc3.html',
  },
  {
    name: 'Yakama Nation Department of Revenue',
    fire: 'Slide Ranch Fire',
    type: 'financial donation resource',
    activeStart: '2024-06-28',
    activeEnd: '2024-07-11',
    opened: 'Accepted monetary donations for families affected by the Slide Ranch Fire',
    address: '401 Fort Rd, Toppenish, WA',
    city: 'Toppenish',
    lat: 46.3774,
    lon: -120.3087,
    sourceName: 'Yakama Nation fire response release',
    sourceUrl: 'https://www.yakama.com/wp-content/uploads/2024/06/Fire-response-June-2024.pdf',
  },
  {
    name: 'Lake Roosevelt High School Gym',
    fire: 'Swawilla Fire',
    type: 'evacuation center',
    activeStart: '2024-07-24',
    activeEnd: '2024-07-27',
    opened: 'Opened July 2024 for Swawilla Fire evacuees',
    address: '505 Crest Dr, Coulee Dam, WA',
    city: 'Coulee Dam',
    lat: 47.9666,
    lon: -118.9889,
    sourceName: 'InciWeb Swawilla daily update',
    sourceUrl: 'https://inciweb.wildfire.gov/node/318681',
  },
  {
    name: 'Paschal Sherman Indian School',
    fire: 'Swawilla Fire',
    type: 'evacuation center',
    activeStart: '2024-07-26',
    activeEnd: '2024-07-27',
    opened: 'Opened July 2024 for Swawilla Fire evacuees',
    address: '169 North End Omak Lake Rd, Omak, WA',
    city: 'Omak',
    lat: 48.4388,
    lon: -119.5270,
    sourceName: 'Swawilla Fire incident summary',
    sourceUrl: 'https://en.wikipedia.org/wiki/Swawilla_Fire',
  },
  {
    name: 'Republic Fairgrounds',
    fire: 'Swawilla Fire',
    type: 'evacuation center',
    activeStart: '2024-07-27',
    activeEnd: '2024-07-29',
    opened: 'Opened July 2024 as Swawilla Fire evacuation needs shifted',
    address: 'Republic, WA',
    city: 'Republic',
    lat: 48.6482,
    lon: -118.7378,
    sourceName: 'Swawilla Fire incident summary',
    sourceUrl: 'https://en.wikipedia.org/wiki/Swawilla_Fire',
  },
  {
    name: 'Columbia High School',
    fire: 'Williams Mine Fire',
    type: 'Red Cross shelter',
    activeStart: '2024-08-05',
    activeEnd: '2024-08-07',
    opened: 'Opened August 2024 for people displaced by the Williams Mine Fire',
    address: '1455 NW Bruin Country Rd, White Salmon, WA',
    city: 'White Salmon',
    lat: 45.7340,
    lon: -121.5044,
    sourceName: 'Columbia Basin Herald / fire report',
    sourceUrl: 'https://www.aol.com/fire-report-williams-mine-fire-195300294.html',
  },
  {
    name: 'Cheney High School',
    fire: 'Columbia Basin Fire',
    type: 'Red Cross evacuation center',
    activeStart: '2024-07-26',
    activeEnd: '2024-07-27',
    opened: 'Opened July 2024 for Columbia Basin Fire evacuees near Tyler',
    address: '460 N 6th St, Cheney, WA',
    city: 'Cheney',
    lat: 47.4939,
    lon: -117.5747,
    sourceName: 'The Spokesman-Review',
    sourceUrl: 'https://www.spokesman.com/stories/2024/jul/26/fire-near-tyler-prompts-evacuations/',
  },
];

const COMMUNITY_RESOURCE_SITES = [
  {
    name: 'Washington Gorge Action Programs Food Distribution',
    type: 'food bank / resource provider',
    address: '683 SW Rock Creek Dr, Stevenson, WA',
    city: 'Stevenson',
    lat: 45.6927,
    lon: -121.8916,
    sourceName: 'WA Community Care / WAGAP food distribution',
    sourceUrl: 'https://ccwa.doh.wa.gov/search/05da357e-e1b9-5a65-9b15-e255adca2886',
  },
  {
    name: 'Stevenson Food Bank',
    type: 'food bank',
    address: 'Stevenson, WA',
    city: 'Stevenson',
    lat: 45.6957,
    lon: -121.8845,
    sourceName: 'K-LINK community resources',
    sourceUrl: 'https://www.klickitatcollaboration.org/community-resources',
  },
  {
    name: 'Goldendale Community Food Bank',
    type: 'food bank',
    address: 'Goldendale, WA',
    city: 'Goldendale',
    lat: 45.8207,
    lon: -120.8217,
    sourceName: 'K-LINK community resources',
    sourceUrl: 'https://www.klickitatcollaboration.org/community-resources',
  },
  {
    name: 'Klickitat Food Bank',
    type: 'food bank',
    address: 'White Salmon, WA',
    city: 'White Salmon',
    lat: 45.7276,
    lon: -121.4865,
    sourceName: 'K-LINK community resources',
    sourceUrl: 'https://www.klickitatcollaboration.org/community-resources',
  },
  {
    name: 'Food Lifeline Hunger Solution Center',
    type: 'regional food resource network',
    address: '815 S 96th St, Seattle, WA',
    city: 'Seattle',
    lat: 47.5160,
    lon: -122.3224,
    sourceName: 'Food Lifeline food resources',
    sourceUrl: 'https://foodlifeline.org/food-resources-portal',
  },
  {
    name: 'Northwest Harvest SODO Community Market',
    type: 'food market / food bank',
    address: '1915 4th Ave S, Seattle, WA',
    city: 'Seattle',
    lat: 47.5850,
    lon: -122.3292,
    sourceName: 'Northwest Harvest',
    sourceUrl: 'https://www.northwestharvest.org/get-help/',
  },
  {
    name: 'Second Harvest Spokane',
    type: 'regional food bank',
    address: '1234 E Front Ave, Spokane, WA',
    city: 'Spokane',
    lat: 47.6608,
    lon: -117.3936,
    sourceName: 'Second Harvest',
    sourceUrl: 'https://2-harvest.org/get-help/',
  },
  {
    name: 'Salvation Army Spokane Food Bank',
    type: 'food bank',
    address: '204 E Indiana Ave, Spokane, WA',
    city: 'Spokane',
    lat: 47.6751,
    lon: -117.4075,
    sourceName: 'Salvation Army Spokane',
    sourceUrl: 'https://spokane.salvationarmy.org/spokane_citadel/cure-hunger/',
  },
  {
    name: 'Yakima Rotary Food Bank',
    type: 'food bank',
    address: '703 Central Ave, Yakima, WA',
    city: 'Yakima',
    lat: 46.5958,
    lon: -120.4963,
    sourceName: 'Yakima Rotary Food Bank',
    sourceUrl: 'https://yakimarotaryfoodbank.org/',
  },
  {
    name: 'OIC of Washington Food Bank',
    type: 'food and community resource',
    address: '815 Fruitvale Blvd, Yakima, WA',
    city: 'Yakima',
    lat: 46.6127,
    lon: -120.5228,
    sourceName: 'OIC of Washington',
    sourceUrl: 'https://www.yvoic.org/',
  },
  {
    name: 'FISH Community Food Bank',
    type: 'food bank',
    address: '804 Elmview Rd, Ellensburg, WA',
    city: 'Ellensburg',
    lat: 46.9968,
    lon: -120.5620,
    sourceName: 'FISH Community Food Bank',
    sourceUrl: 'https://kvfish.org/',
  },
  {
    name: 'Chelan Valley Hope',
    type: 'community resource center',
    address: 'Chelan, WA',
    city: 'Chelan',
    lat: 47.8408,
    lon: -120.0168,
    sourceName: 'Chelan Valley Hope',
    sourceUrl: 'https://chelanvalleyhope.org/',
  },
  {
    name: 'Community Cupboard',
    type: 'food pantry',
    address: 'Leavenworth, WA',
    city: 'Leavenworth',
    lat: 47.5962,
    lon: -120.6615,
    sourceName: 'Upper Valley MEND',
    sourceUrl: 'https://uvmend.org/community-cupboard/',
  },
  {
    name: 'Clark County Food Bank',
    type: 'regional food bank',
    address: '6502 NE 47th Ave, Vancouver, WA',
    city: 'Vancouver',
    lat: 45.6700,
    lon: -122.6229,
    sourceName: 'Clark County Food Bank',
    sourceUrl: 'https://www.clarkcountyfoodbank.org/foodfinder',
  },
  {
    name: 'Bellingham Food Bank',
    type: 'food bank',
    address: '1824 Ellis St, Bellingham, WA',
    city: 'Bellingham',
    lat: 48.7561,
    lon: -122.4741,
    sourceName: 'Bellingham Food Bank',
    sourceUrl: 'https://www.bellinghamfoodbank.org/',
  },
  {
    name: 'Thurston County Food Bank',
    type: 'food bank',
    address: '220 Thurston Ave NE, Olympia, WA',
    city: 'Olympia',
    lat: 47.0470,
    lon: -122.9000,
    sourceName: 'Thurston County Food Bank',
    sourceUrl: 'https://thurstoncountyfoodbank.org/',
  },
  {
    name: 'Nourish Pierce County',
    type: 'food bank network',
    address: 'Tacoma, WA',
    city: 'Tacoma',
    lat: 47.2529,
    lon: -122.4443,
    sourceName: 'Nourish Pierce County',
    sourceUrl: 'https://nourishpc.org/need-food/',
  },
  {
    name: 'Volunteers of America Everett Food Bank',
    type: 'food bank',
    address: 'Everett, WA',
    city: 'Everett',
    lat: 47.9789,
    lon: -122.2021,
    sourceName: 'Volunteers of America Western Washington',
    sourceUrl: 'https://www.voaww.org/foodbank',
  },
  {
    name: 'Community Action Center Food Bank',
    type: 'food bank',
    address: '350 SE Fairmont Rd, Pullman, WA',
    city: 'Pullman',
    lat: 46.7209,
    lon: -117.1764,
    sourceName: 'Community Action Center',
    sourceUrl: 'https://www.cacwhitman.org/food-bank',
  },
];


function matchingCities() {
  const q = searchQuery.trim().toLowerCase();
  if (!q) return [];

  return WASHINGTON_CITIES
    .filter(city => city.name.toLowerCase().startsWith(q))
    .sort((a, b) => a.name.localeCompare(b.name));
}
